### ISSUE TITLE
list of priority levels

### ISSUE THREAD

**Issue by arjunnn** [citizensvs/cvc19backend#2]
Hi @shriram94, please provide a list of priority levels for issues. Right now I've used the following:

1. low
2. medium
3. high
4. critical

**Comment by shriram94** [comment]
@arjunnn 

Add one another class to this "Unspecified" - Default Priority.
That is becausePriority will be seen only on the Gov Monitor and it is for them to update one.
Clarification : So statuses and priorities aren't going to show up on User Views.

**Comment by arjunnn** [comment]
Priorities: ok
Statuses: as a user I can’t see the status of my issue?

**Comment by shriram94** [comment]
Are you going to give a track my issues feature on the User View?
If yes, proceed with it.
@arjunnn

**Comment by arjunnn** [comment]
yes, would be good for the user to know the status of their issues imo

**Comment by shriram94** [comment]
Let's do it then. I am unsure of how far we may go with the twitter view as the permissions are still not given and we're running out of time.
